class UaS_LaserLightModule : HDPickup {
	int mode;
	bool activated;
	UaS_LLM_Emitter emitter;
	vector3 oldsc;

	default {
		Inventory.Amount 1;
		Inventory.MaxAmount 1;
		Inventory.PickupMessage "Picked up a combo laser/light module.";
		Inventory.Icon "CLIPA0";
		HDPickup.Bulk 5;
		HDPickup.refid UAS_HDLD_LASERLIGHT;
		tag "Light/Laser module";
	}

	override bool Use(bool pickup) {
		if (owner.player.cmd.buttons & BT_USE) {
			mode++;
			if (mode > 2) { mode = 0; }
			return false;
		}
		activated = !activated;
		return false;
	}

	override void DoEffect() {
		if(activated) {
			if (!emitter) { emitter = UaS_LLM_Emitter(actor.spawn("UaS_LLM_Emitter", owner.pos, false)); }
			UpdateEmitter();
			switch (mode) {
				case 0: //Flashlight
					Light(true);
					Laser(false);
					break;
				case 1: //Laser
					Light(false);
					Laser(true);
					break;
				case 2: //Both
					Light(true);
					Laser(true);
					break;
			}
		}
		else if (emitter) { emitter.destroy(); }
	}

	void UpdateEmitter() {
		HDPlayerPawn p = HDPlayerPawn(owner);
		actor sc = p.scopecamera;
		vector3 newpos = owner.vec3Angle(
			8 * cos(-sc.pitch) + 4 * sin(-sc.pitch),
			sc.angle,
			(8 * sin(-sc.pitch)) + (owner.player.viewz - owner.pos.z) - 4);
		newpos.z = min(
			newpos.z,
			owner.pos.z + HDWeapon(HDPlayerPawn(owner).player.readyweapon).GetShootOffset(owner));
		emitter.setOrigin(newpos, true);
		emitter.A_SetAngle(sc.angle, true);
		emitter.A_SetPitch(sc.pitch, true);
		emitter.vel = owner.vel;
	}

	void Light(bool on) {
		if (!on) { emitter.Deactivate(self); return; }

		emitter.Activate(self); // turn on dynlight
		HDPlayerPawn p = HDPlayerPawn(owner);
		actor sc = p.scopecamera;

		// Draw flashlight particle beam
		int start = 1; //particle beam starts at emitter
		if(owner.CheckLocalView()) { start = 16; } // unless local player
		for (double d = start; d < 64; d = d + (d / 2)) {
			emitter.A_SpawnParticle("White", SPF_FULLBRIGHT|SPF_RELANG,
				1, (sin(20) * d * 8), 0,
				cos(sc.pitch) * cos(sc.angle) * (d),
				cos(sc.pitch) * sin(sc.angle) * (d),
				sin(-sc.pitch) * (d),
				0, 0, 0,
				0, 0, 0,
				(0.75) / (d ** 1.1), 0, 0);
		}
	}

	void Laser(bool on) {
		if (!on) { return; }
		HDPlayerPawn p = HDPlayerPawn(owner);
		actor sc = p.scopecamera;

		// Draw laser particle beam
		FLineTraceData laserTrace;
		sc.LineTrace(sc.angle, 16384, sc.pitch, TRF_THRUACTORS, data: laserTrace);
		for (double f = 8; f < laserTrace.distance; f = f + random(32, 128)) {
			double bliplength = random(8, 32);
			for (double d = f; d < f + bliplength; d = d + frandom(0.1, 1.5)) {
				float coloroffset = random(0, 128);
				emitter.A_SpawnParticle("GREEN", SPF_FULLBRIGHT|SPF_RELANG,
					1, frandom(0.5, 1.0) * clamp(d/4096, 0.5, 1), 0,
					cos(sc.pitch) * cos(sc.angle) * (d),
					cos(sc.pitch) * sin(sc.angle) * (d),
					sin(-sc.pitch) * (d),
					0, 0, 0,
					0, 0, 0,
					frandom(0.5, 1.0) * clamp(d/32, 0.0, 1), -1, 0);
			}
			f += bliplength;
		}
	}

	override int getsbarnum(int flags){ return mode; }

	override inventory CreateTossable(int amt) {
		if(emitter) { emitter.destroy(); }
		return super.CreateTossable(amt);
	}

	/*
	override void actualpickup(actor other) {
		super.actualpickup(other);
		UaS_Respirator pu = UaS_Respirator(other.findinventory("UaS_Respirator", false));
		pu.capacity = capacity;
	}*/
}

class UaS_LLM_Emitter : DynamicLight {
	default {
		DynamicLight.Type "Point";
		+DYNAMICLIGHT.ATTENUATE;
		+DYNAMICLIGHT.SPOT
	}

	override void PostBeginPlay() {
		super.PostBeginPlay();
		Deactivate(self);
		args[DynamicLight.LIGHT_RED] = 255;
		args[DynamicLight.LIGHT_GREEN] = 255;
		args[DynamicLight.LIGHT_BLUE] = 255;
		args[DynamicLight.LIGHT_INTENSITY] = 255;
		SpotInnerAngle = 15;
		SpotOuterAngle = 25;

	}
}


/*
class UaS_PlayerLaser : HDPickup {
	UaS_PlayerLaser_actual laseractual;

	default {
		Inventory.Amount 1;
		Inventory.MaxAmount 1;
		Inventory.PickupMessage "Picked up a laser sight.";
		Inventory.Icon "CLIPA0";
		//HDPickup.Bulk 5;
		HDPickup.refid UAS_HDLD_LASERLIGHT;
		tag "Laser sight module";
		-INVENTORY.INVBAR;
		-HDPickup.FitsInBackpack;
		+HDPickup.NotInPockets;
		+HDPickup.NeverShowInPickupManager;
	}

	override bool Use(bool pickup) {
		laseractual.active = !laseractual.active;
		return false;
	}

	override void DoEffect() {
		super.DoEffect();
		if(!laseractual) {
			laseractual = UaS_PlayerLaser_actual(actor.spawn('UaS_PlayerLaser_actual', owner.pos));
			laseractual.followtarget = HDPlayerPawn(owner);
		}
	}
}

class UaS_PlayerLaser_actual : Actor {
	actor followTarget;
	rotationinfo rot;
	rotationinfo oldrot;
	vector3 targetPos;
	rotationInfo targetRot;
	bool targetKilled;
	actor actualLight;
	bool active;
	int offsetAngle, offsetPitch;
	double brightness;
	color laserColor, templasercolor;
	bool laser;
	actor laserdot;

	default {
		radius 2;
		height 4;
		+THRUACTORS;
		+NOBLOCKMONST;
		+NOINTERACTION;
	}

	override void Tick() {
		super.Tick();
		if (!followtarget) { destroy(); return; }
		if (!HDPlayerPawn(followtarget)) { destroy(); return; }
		if (!HDPlayerPawn(followtarget).scopecamera) { destroy(); return; }

		// lower laser in response to weapon lowering
		// commenting out, don't really like this as it messes up the scope camera tracking
		/*double temppitch = HDPlayerPawn(followTarget).scopecamera.pitch;
		let rw=hdplayerpawn(followtarget).player.readyweapon;
		if(rw && (rw.InStateSequence(CurState, ResolveState("deselect")) || rw.InStateSequence(CurState, ResolveState("select")))) {
			let psp = hdplayerpawn(followtarget).player.GetPSprite(PSP_WEAPON);
			if(psp) temppitch += (psp.y - 32) / 2.0;
			console.printf(""..psp.y);
		}

		rot.a = -deltaangle(HDPlayerPawn(followTarget).scopecamera.angle, oldrot.a);
		rot.p = -deltaangle(HDPlayerPawn(followTarget).scopecamera.pitch, oldrot.p);

		targetpos = followTarget.vec3Angle(
			6 * cos(followtarget.pitch) + 2 * sin(-followtarget.pitch),
			followTarget.angle + 8 * sin(-followtarget.pitch),
			(6 * sin(-followtarget.pitch)) + (HDPlayerPawn(followTarget).player.viewz - followtarget.pos.z) * 0.90, false);

		targetpos.z = min(
			targetpos.z,
			followtarget.pos.z + HDWeapon(HDPlayerPawn(followtarget).player.readyweapon).GetShootOffset(followtarget));
		//console.printf(""..HDWeapon(HDPlayerPawn(followtarget).player.readyweapon).GetShootOffset(followtarget));

		vel.x += DampedSpring(pos.x, targetpos.x, vel.x, 1, 1);
		vel.y += DampedSpring(pos.y, targetpos.y, vel.y, 1, 1);
		vel.z += DampedSpring(pos.z, targetpos.z, vel.z, 1, 1);

		bool validweapon = (
			!(hdplayerpawn(followtarget).player.readyweapon is 'NullWeapon') &&
			!(hdplayerpawn(followtarget).player.readyweapon is 'HDFist') &&
			!(hdplayerpawn(followtarget).player.readyweapon is 'HDGrenadeThrower') &&
			!(hdplayerpawn(followtarget).player.readyweapon is 'Tripwire') &&
			!(hdplayerpawn(followtarget).player.readyweapon is 'Lumberjack') &&
			!(hdplayerpawn(followtarget).player.readyweapon is 'HDWoundFixer'));

		if (active && validweapon) {
			lasercolor = "GREEN";
			// Draw laser
			FLineTraceData laserTrace;
			LineTrace(angle, 16384, pitch, TRF_THRUACTORS, data: laserTrace);
			for (double f = 1; f < laserTrace.distance; f = f + random(1, f)) {
				double bliplength = random(8, 32);
				for (double d = f; d < f + bliplength; d = d + frandom(0.1, 1.5)) {
					float coloroffset = random(0, 128);
					templasercolor = lasercolor;
					templasercolor.r = clamp(templasercolor.r + coloroffset, 0, 255);
					templasercolor.g = clamp(templasercolor.g + coloroffset, 0, 255);
					templasercolor.b = clamp(templasercolor.b + coloroffset, 0, 255);
					A_SpawnParticle(templasercolor, SPF_FULLBRIGHT|SPF_RELANG,
						1, frandom(0.5, 1.0), 0,
						(cos(pitch) * cos(angle) * d),// + frandom(0.01, 0.05),
						(cos(pitch) * sin(angle) * d),// + frandom(0.01, 0.05),
						(sin(-pitch) * d),// + frandom(0.01, 0.05),
						-rot.a * cos(pitch) * sin(angle) * (d/56.0) + vel.x,
						rot.a * cos(pitch) * cos(angle) * (d/56.0) + vel.y,
						-rot.p * cos(pitch) * (d/56.0) + vel.z,
						0, 0, 0,
						frandom(0.5, 1.0), -1, 0);
				}
				f += bliplength;
			}
		}

		A_SetAngle(HDPlayerPawn(followTarget).scopecamera.angle, true);
		A_SetPitch(HDPlayerPawn(followTarget).scopecamera.pitch, true);

		oldrot.a = HDPlayerPawn(followTarget).scopecamera.angle;
		oldrot.p = HDPlayerPawn(followTarget).scopecamera.pitch;
	}

	double DampedSpring(double p, double r, double v, double k, double d) {
		return -(d * v) - (k * (p - r));
	}
}
*/
