class SlingInitialized : Inventory {}

class UaS_Sling_Bootstrap : EventHandler {
	//initialize additional player inventory
	override void PlayerEntered(PlayerEvent e) {
		PlayerInfo player = players[e.PlayerNumber];
		if(UaS_SlingEnabled == true) {
			if(!player.mo.countinv("SlingInitialized")) {
				player.mo.giveinventory("UaS_WeaponSling", 1);
			}
		}
		else {
			player.mo.TakeInventory("SlingInitialized", 1);
			player.mo.TakeInventory("UaS_WeaponSling", 1);
		}
	}
}
