extend class UaS {
	static play string WrapFunction(string towrap, int wraplen = 30) {
		string r;
		string templine;
		array<string> wrapwords;
		towrap.Split(wrapwords, " ", false);
		for (int i=0; i<wrapwords.size(); i++) {
			templine = templine..wrapwords[i].." ";
			if (templine.length()>wraplen) {
				r = r..templine.."\n";
				templine = "";
			}
		}
		r = r..templine.."\n";
		return r;
	}
}
