extend class UaS {
	//transient cvar tempCheckCVar;

	static play bool CVarCheck(string toCheck, int pnum = -1) {
		cvar tempCheckCVar = null;
		if (pnum >= 0) { tempCheckCVar = CVar.GetCVar(toCheck, players[pnum]); }
		else { tempCheckCVar = CVar.GetCVar(toCheck); }
		if (!tempCheckCVar) {
			//console.printf("UaS Debug Warning: CVar "..toCheck.." not found.");
			return false;
		}
		return true;
	}
}
