class UaS_Bootstrap : EventHandler {
	transient cvar deathfade;

	override void WorldTick() {
		for (int i = 0; i < MAXPLAYERS; i++) {
			if (!playeringame[i]) { continue; }
			if (UaS_AdvancedAIEnabled && UaS_AI_Stealth) { Stealth_PlayerBootstrap(i); }
		}
	}
}

extend class UaS_BootStrap {
	void Stealth_PlayerBootstrap(int pnum) {
		PlayerInfo p = players[pnum];
		if (!p.mo) { return; }
		if (!p.mo.countinv("UaS_StealthHandler")) {
			p.mo.Giveinventory("UaS_StealthHandler", 1);
		}
	}
}
