class UaS_Ration : HDPickup {
	default {
		inventory.pickupmessage "Picked up some food.";
		inventory.MaxAmount 16;
		hdpickup.bulk 6;
		scale 0.3;
		-INVENTORY.INVBAR;
		+INVENTORY.IGNORESKILL;
	}

	States {
		Spawn:
			HSCV A -1;
			stop;
	}
}

class UaS_EmptyRation : HDDebris {
	default {
		scale 0.25;
		bouncesound "misc/wallchunks";
		bouncefactor 0.3;
		-FORCEXYBILLBOARD;
	}

	States {
		Spawn:
			HSCV D 1;
			Loop;
		Death:
			HSCV D -1;
			stop;
	}
}
