class ReloaderInitialized : Inventory {}

class UaS_Reloader_Bootstrap : EventHandler {
	//initialize additional player inventory
	override void PlayerEntered(PlayerEvent e) {
		PlayerInfo player = players[e.PlayerNumber];
		if(UaS_ReloaderEnabled == true) {
			if(!player.mo.countinv("ReloaderInitialized")) {
				player.mo.giveinventory("UaS_Reloader", 1);
			}
		}
		else {
			player.mo.TakeInventory("ReloaderInitialized", 1);
			player.mo.TakeInventory("UaS_Reloader", 1);
		}
	}
}