class UaS_Looting_Bootstrap : EventHandler {
	override void WorldTick() {
		for (int i = 0; i < MAXPLAYERS; i++) {
			if (!playeringame[i]) { continue; }
			PlayerInfo p = players[i];
			if (!p.mo) { return; }
			if (!p.mo.countinv("UaS_Looting_Handler")) {
				p.mo.giveinventory("UaS_Looting_Handler", 1);
				UaS.LogDebug(DBG_Looting, string.format("Looting: Player "..i.." given tracker."));
			}
		}
	}
}
