mixin class UaS_SmallMREItem {
	default {
		UaS_Consumable.Calories 400;
		UaS_Consumable.Fluid 200;
		UaS_Consumable.Bulk 12;
		+UaS_Consumable.PACKAGED;
		Inventory.PickupMessage "$UAS_MIXIN_SMALLMRE_PICKUP";
		scale 0.65;
	}
}

class UaS_LentilChili : UaS_Consumable {
	mixin UaS_SmallMREItem;
	default {
		tag "$UAS_CONSUMABLE_LENTILCHILI_TAG";
		UaS_Consumable.Description "$UAS_CONSUMABLE_LENTILCHILI_DESCRIPTION";
	}
	override void Messages() {
		AddOpenText("$UAS_CONSUMABLE_LENTILCHILI_OPENTEXT");
		AddConsumeText("$UAS_CONSUMABLE_LENTILCHILI_CONSUMETEXT_1");
		AddConsumeText("$UAS_CONSUMABLE_LENTILCHILI_CONSUMETEXT_2");
	}
}

class UaS_BreakfastHashbrowns : UaS_Consumable {
	mixin UaS_SmallMREItem;
	default {
		tag "$UAS_CONSUMABLE_BREAKFASTHASHBROWNS_TAG";
		UaS_Consumable.Description "$UAS_CONSUMABLE_BREAKFASTHASHBROWNS_DESCRIPTION";
	}
	override void Messages() {
		AddOpenText("$UAS_CONSUMABLE_BREAKFASTHASHBROWNS_OPENTEXT_1");
		AddOpenText("$UAS_CONSUMABLE_BREAKFASTHASHBROWNS_OPENTEXT_2");
		AddConsumeText("$UAS_CONSUMABLE_BREAKFASTHASHBROWNS_CONSUMETEXT_1");
		AddConsumeText("$UAS_CONSUMABLE_BREAKFASTHASHBROWNS_CONSUMETEXT_2");
	}
}

class UaS_CacoGiblets : UaS_Consumable {
	mixin UaS_SmallMREItem;
	default {
		tag "$UAS_CONSUMABLE_CACOGIBLETS_TAG";
		UaS_Consumable.Description "$UAS_CONSUMABLE_CACOGIBLETS_DESCRIPTIOn";
	}
	override void Messages() {
		AddOpenText("$UAS_CONSUMABLE_CACOGIBLETS_OPENTEXT_1");
		AddOpenText("$UAS_CONSUMABLE_CACOGIBLETS_OPENTEXT_2");
		AddConsumeText("$UAS_CONSUMABLE_CACOGIBLETS_CONSUMETEXT_1");
		AddConsumeText("$UAS_CONSUMABLE_CACOGIBLETS_CONSUMETEXT_2");
		AddConsumeText("$UAS_CONSUMABLE_CACOGIBLETS_CONSUMETEXT_3");
		AddConsumeText("$UAS_CONSUMABLE_CACOGIBLETS_CONSUMETEXT_4");
	}
}
