#!/bin/bash
cd ..

# =========================
# ZSCRIPT
# =========================
echo "// Autogenerated " > zscript.zsc
echo >> zscript.zsc
echo "version \"4.5\"" >> ./zscript.zsc
echo >> zscript.zsc

# the weirdass sort commands are to make sure the files are included in the correct order
# Core
for f in $(find * -name "core*.zsc" -not -path "*zscript.zsc" | sort -t '/' -k1,1 -k3r )
do
	ifile=$(basename $f)
	ipath=$(dirname $f)
	echo "#include \"$ipath/$ifile\"" >> ./zscript.zsc
done

# Everything else
for f in $(find * -name "*.zsc" -not -path "*zscript.zsc" -not -path "*core*" | sort -t '/' -k1,1 -k3r )
do
	ifile=$(basename $f)
	ipath=$(dirname $f)
	echo "#include \"$ipath/$ifile\"" >> ./zscript.zsc
done

# =========================
# CVARINFO
# =========================
echo "// Autogenerated " > cvarinfo.txt
echo >> cvarinfo.txt

find \
	-name "cvarinfo.txt" \
	-not -path "./cvarinfo.txt" \
	-exec cat {} + >> ./cvarinfo.txt

# =========================
# MENUDEF
# =========================
rm ./menudef.txt
cat ./core/menudef.txt >> ./menudef.txt
find \
	-name "menudef*" \
	-not -path "./core/*" \
	-not -path "./menudef.txt" \
	-not -path "./core/menudef.txt" \
	-exec cat {} + >> ./menudef.txt

# =========================
# MAPINFO
# =========================
rm ./mapinfo.txt
find \
	-name "mapinfo*" \
	-exec cat {} + >> ./mapinfo.txt

# =========================
## Visual Weapons module textures
# =========================
echo "// Autogenerated " > textures.marines.txt
echo >> textures.marines.txt

for f in $(find visualweapons/sprites/ -type f)
do
	cfile=$(basename $f)
	cpath=$(dirname $f)
	sizex=$(od --endian=little --read-bytes 2 --skip-bytes 0 -t d2 -An $f | tr -d ' ')
	sizey=$(od --endian=little --read-bytes 2 --skip-bytes 2 -t d2 -An $f | tr -d ' ')
	 offx=$(od --endian=little --read-bytes 2 --skip-bytes 4 -t d2 -An $f  | tr -d ' ')
	 offy=$(od --endian=little --read-bytes 2 --skip-bytes 6 -t d2 -An $f  | tr -d ' ')

	echo "sprite $cfile, $sizex, $sizey {" >> textures.marines.txt
	echo " 	patch \"$f\", 0, 0" >> textures.marines.txt
	echo "	offset $offx, $offy }" >> textures.marines.txt
	echo >> textures.marines.txt
done

# =========================
# TEXTURES
# =========================
# rm ./textures.txt
# find \
	# -name "textures*" \
	# -exec cat {} + >> ./textures.txt

# =========================
# SNDINFO
# =========================
# rm ./sndinfo.txt
# find \
	# -name "sndinfo*" \
	# -exec cat {} + >> ./sndinfo.txt