#!/bin/bash

cd ..

echo "// Autogenerated " > zscript.zsc
echo >> zscript.zsc
echo "version \"4.5\"" >> ./zscript.zsc
echo >> zscript.zsc

# Core
for f in $(find -name "core*.zsc" not -path "*zscript.zsc" | sort -r)
do
	ifile=$(basename $f)
	ipath=$(dirname $f)
	echo "#include \"$ipath/$ifile\"" >> ./zscript.zsc
done