#!/bin/bash

cd ..

echo "// Autogenerated " > textures.marines.txt
echo >> textures.marines.txt

for f in $(find visualweapons/sprites/ -type f)
do
	cfile=$(basename $f)
	cpath=$(dirname $f)
	sizex=$(od --endian=little --read-bytes 2 --skip-bytes 0 -t d2 -An $f | tr -d ' ')
	sizey=$(od --endian=little --read-bytes 2 --skip-bytes 2 -t d2 -An $f | tr -d ' ')
	 offx=$(od --endian=little --read-bytes 2 --skip-bytes 4 -t d2 -An $f  | tr -d ' ')
	 offy=$(od --endian=little --read-bytes 2 --skip-bytes 6 -t d2 -An $f  | tr -d ' ')

	echo "sprite $cfile, $sizex, $sizey {" >> textures.marines.txt
	echo " 	patch \"$f\", 0, 0" >> textures.marines.txt
	echo "	offset $offx, $offy }" >> textures.marines.txt
	echo >> textures.marines.txt
done


# sprite [patch name], [patch xsize], [patch ysize] {
    # patch "[big/long/path]", 0, 0
    # offset, [patch xoff], [patch yoff] }