#!/bin/bash

cd ..

echo "// Autogenerated " > zscript.zsc
echo >> zscript.zsc
echo "version \"4.5\"" >> ./zscript.zsc
echo >> zscript.zsc

find ./core/module/ \
	-name "*.zsc" \
	-not -path "*zscript.zsc" \
	| sort -r | sed -e 's/^\.\///' \
	-exec echo "#include \"$i\"" >> ./zscript.zsc

find \
	-name "*.zsc" \
	-not -path "*zscript.zsc" \
	-not -path "./core*" \
	| sort -r | sed -e 's/^\.\///' \
	-exec echo "#include \"$i\"" >> ./zscript.zsc
